### ISSUE TITLE
0.0.6(only supermarket.chef.io) has problem for the install of phar

### ISSUE THREAD

**Issue by mtak3** [djoos-cookbooks/phpcpd#2]
https://supermarket.chef.io/cookbooks/phpcpd/versions/0.0.6
There is a problem with the recipe for the install of phar of cookbooks.
There are no tags 0.0.6 in this repository. That's different from the master branch.
Since the problem in the master branch is resolved, please update of chef supermarket.

**Comment by djoos** [comment]
Thanks for flagging this @mtak3, we've just pushed 1.0.0 to the Chef supermarket!

Kind regards,
David
